[package]
name = "gsc_timereset"
version = "0.1.0"
edition = "2018"
description = "GSC time reset password calculator"
readme = "README.md"
repository = "https://github.com/ignacio-ts/randtoken"
license = "GPL-3.0"
keywords = ["videogame", "calculator", "mons", "gsc"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
